index.ios.js

Reverts EstebanFuentealba/react-native-share#4

Revert "updateRN 0.14.0 new native module Api"

---

README.md

Updated README for RN 0.19

---

android/src/main/java/cl/json/RNShareModule.java

- Refactored code into reusable methods. 
- Added documentation to new methods.
- Simplified code in `open` method

Improved abstractions for Android implementation

---

README.md

function returned promise is worth documented

---

ios/EmailShare.h
ios/GenericShare.h
ios/GooglePlusShare.h
ios/RNShare.h
ios/RNShare.m
ios/WhatsAppShare.h

See work from code push : 
https://github.com/Microsoft/react-native-code-push/pull/670

Support RN 0.39.2 and 0.40.0

---

ios/GenericShare.m
ios/WhatsAppShare.m

Support Whatsapp URL sharing

---

android/src/main/java/cl/json/ShareFile.java

Fix for NullPointerException on HTC 10 issue #131
Had issues opening .lnk files on HTC 10, needed a cursor null check.

Added null check for cursor and cursor.moveToFirst()

---

index.js

BackAndroid is deprecated

---

android/src/main/java/cl/json/RNShareModule.java
ios/RNShare.m

To make it more clear what's going wrong.

rephrase error message

---

android/src/main/java/cl/json/ShareFile.java

Sorry, I've forgot that `&&` Java operator only works with booleans.

Fix check with Java way

---

components/Button.js
components/Overlay.js
components/Sheet.js

1) Removed unused code
2) Removed class when it was not necessary

Simplify JavaScript code in components

---

README.md

Continuing #197 after making it work in actual app.

Update README  

---

README.md

Add missing Android documentation

---

android/build.gradle

this PR is based in [issue #252](https://github.com/react-native-community/react-native-share/issues/252)

config to wide gradle configuration support

---

android/build.gradle

Fixes https://github.com/react-native-community/react-native-share/issues/266
Taken from how it's done in react-native-camera
https://github.com/react-native-community/react-native-camera/blob/a4599093ea984e83f33bb92e33bb09e1078ddc01/android/build.gradle

Fix DEFAULT_SUPPORT_LIB_VERSION

---

README.md

refactor doc how to use the method open

---

ios/GenericShare.m

Change "message" parameter to "text": https://dev.twitter.com/web/tweet-button/web-intent

Fix twitter fallback text

---

ios/GenericShare.m

Change twitter text fallback

---

README.md

One of the example had an syntax error

Fix syntax error in example code

---

.npmignore

I have added some lines that I think are not needed in the npm release. Please look into this and let me know if anything else needs to added or removed from here.

Added npmignore

---

android/build.gradle

Android def cleanup: add a ternary based function with fallback, just a little improved version rather then having many explicit def for each value.

little improvement over too many "def"

---

circle.yml

as we upgraded from 26+ to 27 thus make sense to upgrade build tool as well.

updated android build-tool - CircleCI

---

android/build.gradle

ref to closed PR https://github.com/react-native-community/react-native-share/pull/311

Update obsolete compile to implementation

---

RNShare.podspec

fix directory git of project

---

.github/ISSUE_TEMPLATE.md

feat(issue-template): add issue template

---

components/Overlay.js

Fix flow type of state.overlayStyle mentioned in #341 .

fix flow type of state.overlayStyle

---

android/src/main/java/cl/json/social/SingleShareIntent.java

[Android] Fix SingleShareIntent to always call super.open

---

README.md

avoid side effects by specifying pkg

rn link react-native-share

---

android/src/main/java/cl/json/social/SingleShareIntent.java

We discover an issue with SingleShare on Android. Details explained here #344

Fix singleShare for social Media

---

README.md
android/src/main/java/cl/json/RNShareModule.java
android/src/main/java/cl/json/social/PinterestShare.java
index.js

Hello,
Here is the system to share on pinterest on android
I'm not the skills for IOs, so don't hesitate to take over the PR:)

Add pinterest in ANDROID

---

README.md
android/src/main/java/cl/json/RNShareModule.java
android/src/main/java/cl/json/social/ShareIntent.java
example/App.js
index.js

This way consumers of this package can also check if a package is installed, which will make this package even more useful.

expose isPackageInstalled 

---

README.md

I tried to use the code as is and got a promise rejection

DOC/FIX - message property is mandatory

---

README.md
android/src/main/java/cl/json/RNShareModule.java
android/src/main/java/cl/json/social/MessengerShare.java
android/src/main/java/cl/json/social/SMSShare.java
android/src/main/java/cl/json/social/SnapChatShare.java

I have added Sms, Snapchat and messenger share feature for Android. But I don't know about iOS.

Add sms, snapchat and messenger share feature for Android

---

README.md
index.js
ios/InstagramStories.h
ios/InstagramStories.m
ios/RNShare.m
ios/RNShare.xcodeproj/project.pbxproj

Hi,
It's an iOS Instagram Stories Share implementation. 
https://developers.facebook.com/docs/instagram/sharing-to-stories

Instagram stories

---

.eslintrc
index.js
package.json
yarn.lock

Removing all lint rules and applying react-native-community lint
Run a `yarn lint` to check if there a any lint errors

Adding react-native-community lint

---

example/__tests__/Failed.test.js
example/__tests__/Succeed.test.js
example/__tests__/__snapshots__/Succeed.test.js.snap
example/components/Failed.js
example/components/Succeed.js
example/package.json
example/yarn.lock

Implemented two tests (one succeed and one failed) for bug illustrating which described in issue #407

Implemented succeed and failed test 

---

CODEOWNERS

see https://github.com/react-native-community/.github/issues/1#issuecomment-496203158
cc @kelset

chore(codeowners): add CODEOWNERS file

---

README.md
android/src/main/java/cl/json/RNShareModule.java
android/src/main/java/cl/json/social/LinkedinShare.java
index.js

I have added linkedin share feature for Android.

Add linkedin share feature for Android

---

index.js

Received this error in `node_modules` 
```Error ┈┈┈┈┈ node_modules/react-native-share/index.js:73:52
Cannot create View element because inexact object type [1]
is incompatible with exact $ReadOnly [2] in array element
of property style.
node_modules/react-native-share/index.js
[1]  45│   overlayStyle?: {},
:
70│     const {style = {}, overlayStyle = {}, ...props} = this.props;
71│     return (
72│       <Overlay visible={this.props.visible} {...props}>
73│         <View style={[styles.actionSheetContainer, overlayStyle]}>
74│           <TouchableOpacity
75│             style={shareSheetStyle}
76│             onPress={this.props.onCancel}
77│           />
78│           <Sheet visible={this.props.visible}>
79│             <View style={[styles.buttonContainer, style]}>
80│ …
```

Add type to style and overlayStyle

---

README.md
android/src/main/java/cl/json/RNShareFileProvider.java
android/src/main/java/cl/json/RNShareModule.java
android/src/main/java/cl/json/RNSharePathUtil.java
example/.flowconfig
example/android/app/src/main/AndroidManifest.xml
example/package.json
example/yarn.lock
package.json
yarn.lock

- AndroidX libraries support added
- Fixed Android release build issues with old File Provider libraries
- react-native@0.60.0+ support and auto linking support added
- Updated ReadMe file with usage for eact-native@0.60.0+

AndroidX libraries and react-native@0.60.0+ support

---

README.md

missing directory from readme.
no need

fix missing path

---

android/src/main/java/cl/json/RNShareModule.java
android/src/main/java/cl/json/social/ShareIntent.java

fix #569
I also added stack traces for debugging, that was how I found it
See my comment here to explain what happened - I saw this when I tried to test the updated example from #567 on android. With this fix, the example works.
https://github.com/react-native-community/react-native-share/commit/4050190d12f5aa1e0b3005f7abe342b0e71c164b

fix: social should be optional in android

---

ios/EmailShare.h
ios/EmailShare.m
ios/GenericShare.h
ios/GenericShare.m
ios/GooglePlusShare.h
ios/InstagramShare.h
ios/InstagramShare.m
ios/RNShare.m
ios/WhatsAppShare.h
ios/WhatsAppShare.m

No functionality changes -- only minor edits to code to comply with Xcode warnings (as of Xcode 10.2)
No functionality changes.  Just code semantics.

Fix Xcode warnings

---

android/gradle/wrapper/gradle-wrapper.properties
example/android/gradle/wrapper/gradle-wrapper.properties
example/android/gradlew
example/android/gradlew.bat

- Gradle wrapper `5.6.2`
Successfully tested `./gradlew build` in `android`, as well as `react-native run-android` in `example`.
<sub><sup>Once approved, please use a *normal* GitHub merge (i.e. **NO rebase/squash** merge) to integrate the commit(s) from the PR head branch. The changes are broken up into meaningful, [atomic commits](https://www.freshconsulting.com/atomic-commits/), and my branch should already be up-to-date with the latest base branch. If it isn't, or if you want me to change anything, please let me know, and I will update the branch as soon as possible. Thank you!</sup></sub>

Update Gradle wrapper to 5.6.2

---

index.js

Fixes #585
Tested in private project using real iPhone XR device and simulators

Removed react-native Share dependency

---

android/src/main/AndroidManifest.xml

Remove tools replace that was causing warnings
Run build without problems

Remove unnecessary tools replace on build gradle

---

README.md

chore(readme): mocking with Jest example

---

.circleci/config.yml
example/yarn.lock

copied from: https://github.com/react-native-community/react-native-camera/blob/4705834f08ac3c2a2f0da2ebf0aab6b63b7dbd89/.circleci/config.yml

ci(fix): adapt to new workflow

---

components/Button.js

Just noticed the typing could be better for the `iconSrc` passed as `source` to the `Image` component.
Run flow!

Correctly type image source

---

README.md

Typo fixed on line 65
There is no break on code

Typo fixed on line 65

---

example/App.js

Just a quick follow-up to #600 (several commits were reverted, which also unintentionally undid some formatting fixes).

Fix ESLint errors

---

package.json

This PRS changing the project version to 3.0.0 due to some possible breaking changes, following the last changelog:
958ab6c - Update react-native to 0.61.5 (Frieder Bluemle)
1b3d315 - Update react-native to 0.61.4 (#637) (Frieder Bluemle)
c7287a3 - Update and fix Gradle setup (#588) (Frieder Bluemle)
25f5de6 - set useNativeDriver explicitly for Animations (#633) (James Adams)
86daf53 - correctly type image source (#632) (James Adams)
d88e542 - fix: added missing "v" to `source` field in podspec (#619) (mdstroebel)
736a8ac - iOS 13: Resolve promise if ShareSheet is manually dismissed (#607) (Tom Targosz)
9ad3436 - fix: remove uncessary tools replace on build gradle (luancurti)
4e78f35 - chore(lint): fixing lint errors (MateusAndrade)
56f50cc - fix: instagram-stories build failure …

build: setting project version to 3.0.0

---

.github/stale.yml

I remove duplicate line in `stale.yml`

ci: Remove duplicate line

---

README.md
android/src/main/java/cl/json/ShareFiles.java
android/src/main/java/cl/json/social/ShareIntent.java
index.js

Support setting filename for base64 url and introduces filenames array for urls array for base64 files.
- Fixes #662 
- Fixes #519

[filename] Fixes base64 filename in android

---

.circleci/config.yml
example/metro.config.js

This PR reverts #690  setting the maxWorks directly on the CI env

ci: applying config to set MAX_WORKERS to 2

---

.circleci/config.yml

This PR aims on set the `MAX_WORKERS` correctly the build job

fix ci envs at job

---

RNShare.podspec

Avoid inconsistency of informations with `podspec` and `package.json`
Go to `example/ios` run `pod install` and run example App and everything is working as expected

Update podspec infos using package.json infos

---

README.md

Update from deprecated `compile` to `implementation `

Update readme on section android manual link

---

README.md

Do not ask users to link with React Native 0.60.0

---

android/src/main/java/cl/json/social/ShareIntent.java

excludedActivityTypes was only working for iOS so I decided to make it work on android.
excludedActivityTypes now works for android as well. Tested on both simulator and actual device.

Fix excludedActivityTypes for Android

---

README.md
index.js
ios/RNShare.m
ios/RNShare.xcodeproj/project.pbxproj
ios/RNShareActivityItemSource.h
ios/RNShareActivityItemSource.m

Share sheet was completely renewed in iOS13. It presents a preview of the link.
If this feature isn't supported, the appearance isn't nice.
So I implemented providing data to share by using UIActivityItemSource.
It allows also to share different data according to activities and to customize the share sheet.
Create a new React Native project and change its App.js like example code.
```jsx:App.js
import React from 'react';
import {Platform, Text, TouchableWithoutFeedback, View} from 'react-native';
import Share from 'react-native-share';
const url = 'https://twitter.com/myb/status/1219906294976401408';
const title = 'Twitter';
const message = 'Here I am.';
const App: () => React$Node = () => {
return (
<View style={{flex: 1, justifyContent: 'center', alignItems: 'center'}}> …
```

feat: support UIActivityItemSource to customize share-sheet for iOS 13

---

android/src/main/java/cl/json/social/ShareIntent.java

On sharing an url on android it shares the url inside an array
Fixes #710 
Try to share an url and it shares correctly

Fix share url android

---

package.json

Updating package version to 3.1.0

updating package version to 3.1.0

---

.circleci/config.yml
docs/index.html
package.json
yarn.lock

Reverts react-native-community/react-native-share#733

Revert "Feat/semantic release"

---

README.md

Add xcode 11 to requirements and `LinkPresentation.h file not found` to `Troubleshooting` section
Not applicable

Update requirements to use xcode 11 and ios 13 sdk 

---

ios/RNShareActivityItemSource.m

fix: suppress errors occurred when built with ios sdk 12 or lower

---

README.md

docs: Custom icon usage instructions for iOS share preview added to example

---

website/docs/share-single.mdx

Update to clarify how to share videos to instagram

---

README.md
yarn.lock

Updating CircleiCI status Badge + Testing org config for CI

docs: updating status-badge url + testing CI

---

README.md

Official doc link was wrong.
X

Correct wrong link README.md

---

package.json

fix: homepage URL in package.json

---

package.json

As I have researched **AssetPath** stopped working. https://stackoverflow.com/questions/34226433/instagram-hooks-pre-select-media-issue. had to use **LocalIdentifier**
I have followed this https://github.com/react-native-community/react-native-share/pull/826/files and no issue when previewing video after that.

Instagram Video Preview

---

website/docs/share-package-installed.mdx

Fix typo in Share.isPackageInstalled docs example

---

ios/FacebookStories.m
ios/InstagramStories.m

I found a typo in the local variable name, so I fixed it.

fix typo in local variable name: sticketURL -> stickerURL

---

android/src/main/java/cl/json/RNShareModule.java
android/src/main/java/cl/json/social/FacebookStoriesShare.java
index.js
ios/RNShare.m
website/docs/share-single.mdx

Add Facebook Stories to Android.
There is a small difference in the implementation compared to the current one for iOS:
- The `method` option does not exist, because we can play with the [available parameters](https://developers.facebook.com/docs/sharing/sharing-to-stories/android-developers) and some of them are ignored if provided together (background colors and a background asset, for example), so I decided to ignore it, please let me know what do you think about this.
<details>
<summary>Sample code</summary>
```js
import React, {useCallback, useEffect, useRef, useState} from 'react';
import {AppState, StyleSheet, View, Button, Switch, Text} from 'react-native';
import RNFetchBlob from 'rn-fetch-blob';
import Share from 'react-native-share';
const App = () => {
const appState = …
```

Feat - add Facebook Stories to Android

---

website/docs/installing.mdx

This is mentioned on a different page, but this information is not included on Share.shareSingle method docs. It took me quite a while to understand the problem, I think it would be helpful to put this information on this page.

LSApplicationQueriesSchemes documentation

---

.github/config.yml

Adding the basic config to use [Request Info Bot](https://probot.github.io/apps/request-info/)
Open an empty issue/pr 🚀

chore: adding pr bot config

---

android/src/main/java/cl/json/social/ShareIntent.java
android/src/main/java/cl/json/social/SingleShareIntent.java

Fixes the error from https://github.com/react-native-share/react-native-share/issues/613 in Android 11.

Android: Fix permission denial error

---

Button.d.ts
Overlay.d.ts
Sheet.d.ts
index.d.ts
package.json
yarn.lock

This copies the type declaration files from @types/react-native-share into the repo and links them to package.json.

Added TS type declarations from @types/react-native-share

---

.github/ISSUE_TEMPLATE/bug_report.md

typescript version incompatibilities may happen sometimes
Related #1007

chore(issue-template): request typscript version

---

website/yarn.lock

- Updating web-site deps due to security vulnerability warnings

chore: updating website-deps

---

.circleci/config.yml

- Updating circleci-orb to `5.3.0`
- Updating node-version to deploy docs to `12`
N/A

chore: update orb version + node version for docs

---

android/src/main/java/cl/json/RNShareModule.java
android/src/main/java/cl/json/social/ShareIntent.java
android/src/main/java/cl/json/social/WhatsAppBusinessShare.java
src/index.tsx
src/types.ts
src/typings/react-native.d.ts
website/docs/share-single.mdx

Currently, ShareSingle supporting WhatsApp, Now I have added support for WhatsApp Business too(Android Only).
Fixed the bug [https://github.com/react-native-share/react-native-share/issues/1035](https://github.com/react-native-share/react-native-share/issues/1035)

WhatsApp Business Support For Android

---

.circleci/config.yml

- Updating default branch to `main`
- Changing references from `master` branch to `main`.

ci: changing references from master to main

---

android/src/main/java/cl/json/social/InstagramShare.java
website/docs/share-single.mdx

This introduces a new feature to IG single share. 
I found out how to open share views on IG without providing media.  
As added in docs

feat: IG android - open share screen

---

website/yarn.lock

- Updating website dependencies

fix: updating website deps

---

.github/workflows/codeql-analysis.yml

- Adding an Github action to test CodeQL with react-native

ci(codeql): adding action to run code-ql

---

example/App.js
ios/EmailShare.m
src/index.tsx
src/types.ts
website/docs/share-single.mdx

feat: singleShare supports urls for email

---

android/src/main/java/cl/json/RNShareModule.java
android/src/main/java/cl/json/social/ViberShare.java
ios/RNShare.m
ios/ViberShare.h
ios/ViberShare.m
src/index.tsx
src/types.ts
src/typings/react-native.d.ts
website/docs/share-single.mdx

Supporting  #992 
Including Viber Test in ./example app

feat: singleShare supports for Viber

---

.circleci/config.yml

Updating publish-version job to 16

ci(node): setting publish version to 16

---

android/src/main/java/cl/json/social/InstagramStoriesShare.java
example/App.js
ios/InstagramStories.m
src/index.tsx
src/types.ts

Implemented #1304
https://developers.facebook.com/blog/post/2022/10/10/introducing-important-update-to-Instagram-sharing-to-stories/
https://developers.facebook.com/docs/instagram/sharing-to-stories/

feat(android, iOS)!: require appId for instagram stories to meet new Meta requirement

---

website/docs/troubleshooting-ios.mdx

Spell check in `troubleshooting-ios.mdx` file

Spell check

---

src/components/Button.tsx
src/components/Overlay.tsx
src/components/ShareSheet.tsx
src/components/Sheet.tsx

This MR aims at providing a new implementation of the UI components that makes use of function components, moving away from the class components that were already in place.

Refactor UI components to function components

---

website/docs/share-single.mdx

A Hyper link at https://react-native-share.github.io/react-native-share/docs/share-single is broken

docs: fix broken hyperlink

---

src/index.tsx

https://github.com/react-native-share/react-native-share/issues/1405

Add missing catch

---

src/helpers/options.ts
src/index.tsx

I introduced a regression in [PR#1409](https://github.com/react-native-share/react-native-share/pull/1409). This PR should fix that and I also cleaned up some left-over comments from that PR.

Fix Regression

---

.github/ISSUE_TEMPLATE/bug_report.md

behaviour -> behavior

---

example/App.js

The example is not scrollable, that make it not convenient to debug.
| Before |  After |
| --- | --- |
|  <img width="443" alt="image" src="https://github.com/react-native-share/react-native-share/assets/16508727/921abb00-f091-4a2e-a62c-3821c0a86260"> |  <img width="443" alt="image" src="https://github.com/react-native-share/react-native-share/assets/16508727/c86be848-9c4a-4b8a-bb61-e2cd8da8b1dc"> |
Did in my simulator

Feat: import the example UI layout & add 1 more example function

---

website/docs/share-single.mdx

I struggled with [this error](https://github.com/react-native-share/react-native-share/issues/1436) and wanted to document the solution.
Here's a screenshot from a md editor

#1436: Updated docs about permissions for sharing on ig

---

ios/RNShare.h
ios/RNShare.mm

fixes: https://github.com/react-native-share/react-native-share/issues/1568

fix(ios): import from codegen with RN 0.75+

---

ios/RNShare.h
ios/RNShare.mm

I went too fast before, quotes are needed
https://github.com/react-native-share/react-native-share/pull/1569#issuecomment-2324625152

fix(ios): use quote instead of brackets

---

.circleci/config.yml

- Updating resource-class for iOS build with CircleCI

ci(resource): updating executor to m1

---

android/src/main/java/cl/json/social/ShareIntent.java

This PR introduces the use of **`ClipData`** when sharing files in Android through the `ShareIntent`, which resolves issues related to image preview not appearing when sharing images. This fix ensures proper handling of permissions for sharing both **single** and **multiple** files, improving compatibility across various Android applications. This change addresses the issue discussed in **[#1574](https://github.com/react-native-share/react-native-share/issues/1574)**.
- Added **`ClipData`** support for sharing both **single** and **multiple files** on Android.
- **`ClipData`** helps manage URIs in a more secure and consistent way, ensuring the files are shared properly across apps.
- The usage of `ClipData` ensures that the Android system grants temporary read permissions to the shared …

[Android] Added ClipData for sharing multiple and single files; improved compatibility and preview display

---

android/src/main/java/cl/json/social/InstagramStoriesShare.java
ios/InstagramStories.m
src/types.ts
website/docs/share-single.mdx

Supercedes #1595 - only because github was denying me permission to push back to the PR repo/fork after rebasing it and testing it locally
All information related to this is on that PR
CI appears to be broken so I tested this locally and it appears to work
Closes #1595

feat: Add support for Instagram Stories linkUrl/linkText

---

example/Gemfile
example/Gemfile.lock
example/ios/Podfile.lock
package.json
patches/react-native+0.72.6.patch
website/package.json
website/yarn.lock
yarn.lock

- Updating `example/ios` to fix build issues
- Updating dependencies used by docs

CI- Fixing iOS build issues + updating documentation version

---

.circleci/config.yml
package.json

- Removing post-install, as it was crashing new installations without the patch-package

ci(script): removing post install

---

website/docs/share-single.mdx

Just fixing docs
Naaaaa
Gonna implement it in getnofilter.com in a few days! Awesome job guys!

doc: Fix shareSingle doc

---

example/App.js
example/ios/example/Info.plist
ios/RNShare.mm
ios/TwitterShare.h
ios/TwitterShare.m
website/docs/share-single.mdx

Add twitter/x shareSingle to iOS.
Closes: https://github.com/react-native-share/react-native-share/issues/1648
```jsx
const shareToTwitter = async () => {
const shareOptions = {
message: 'Example Twitter',
url: 'https://google.com',
social: Share.Social.TWITTER,
};
try {
const ShareResponse = await Share.shareSingle(shareOptions);
setResult(JSON.stringify(ShareResponse, null, 2));
} catch (error) {
console.log('Error =>', error);
setResult('error: '.concat(getErrorString(error)));
}
};
```
I didn't check if it's possible to share images, probably yes, it can be added later if necessary.

feat(ios): twitter/x shareSingle
