react-native-share/react-native-share

- android/build.gradle
Reference:
https://github.com/square/okio/issues/58
> Set lint warning for InvalidPackage, instead of error out

- RNShare.m
Add a Url or Image Object item because some App's extension need . otherwise they won't appear in the share sheet  on iOS .
Also i have no idea about  share a Url using Intent in android.  any idea?
> add a url share item

- index.ios.js
- package.json
`peerDependecies` is blocking to use this package out of the box with "rc" version of React Native (eg. 0.19.0-rc)
`invariant` dependency is imported but never used.
> Remove peerDependecies and unnecessary dependency

- README.md
- android/src/main/java/cl/json/RNShareModule.java
- ios/RNShare.m
This also concats URL onto the end of share_text if both are provided on Android. The result means the message sent from Android & iOS now match.
> Add Subject for email sharing

- android/src/main/java/cl/json/RNShareModule.java
- android/src/main/java/cl/json/ShareFile.java
- android/src/main/java/cl/json/social/ShareIntent.java
Allow other kinds of contentUris to be shared, not just from the library, therefore try to get the extension/mime-type from the contentUri itself. Also grant read permissions for sent contentUris.
> Sharing content uris

- README.md
- android/src/main/java/cl/json/ShareFile.java
- android/src/main/java/cl/json/social/ShareIntent.java
On Android (6.0), for some reason that I can't explain, when the mime type of a local file cannot be guessed from its URL I get a `NullPointerException` at https://github.com/EstebanFuentealba/react-native-share/blob/92aaa3f87e88377cdc74c6b272e5b37543473c4a/android/src/main/java/cl/json/ShareFile.java#L90
This happens for instance with files like `myImage.JPG` (case issue), `myFile` (no extension) or `myMarkdown.md` (unknown extension), for which `ShareFile#getMimeType` returns `null`, thus the call to `ShareFile#getRealPathFromURI` in `ShareFile#isLocalFile`.
Note that I download and store files with [react-native-fetch-blob](https://github.com/wkh237/react-native-fetch-blob) configured to use the Android DownloadManager. An example of storage location is …
> Allow to pass file mime type as an option

- ios/GenericShare.m
- ios/WhatsAppShare.m
Adding promise rejection for whatsapp and generic apps on ios.  Don't need to do for email or google plus since they don't rely on specific apps being installed.
> Add promise rejection on iOS if app not installed

- ios/EmailShare.m
- ios/GenericShare.m
- ios/GooglePlusShare.m
- ios/WhatsAppShare.m
I added promise rejection before.  Now adding promise success to round it out.
> Add promise success for singleShare on iOS

- android/build.gradle
From [build.gradle](https://github.com/Microsoft/react-native-code-push/blob/master/android/app/build.gradle#L24):
dependencies {
compile "com.facebook.react:react-native:0.20.+"
}
This means that when adding the react-native-code-push module to an app and building it, Gradle will fetch React Native 0.19 from Maven, even if the app is using say RN 0.34. We stopped releasing the React Native Android artifacts to Maven - they are distributed via npm along with the JS code.  For example I installed RN 0.34 from npm, it will have the 0.34 Android artifacts in `node_modules` and [Gradle will use those to build the app](https://github.com/facebook/react-native/blob/9ee815f6b52e0c2417c04e5a05e1e31df26daed2/local-cli/generator-android/templates/src/build.gradle#L21).
Would you consider using …
> [Android] Let npm take care of versioning

- RNShare.podspec
Podscpec file for adding this dependency to a native iOS project using React Native and Cocoapods. I manage pod version with the version declare in package.json. To test my PR, you have to create a git tag 1.0.16. 
**You will have to create git tag for each version you 'll release**
Just add this in the Podfile after _pod React_
```
pod 'React', :path => '../node_modules/react-native', :subspecs => [
'Core',
'RCTText',
'RCTWebSocket', # needed for debugging
'RCTNetwork'
]
pod 'RNShare', :path => './node_modules/react-native-share'
```
> Add podspec declaration

- components/Overlay.js
> Remove width and height when the overlay is invisible

- android/src/main/java/cl/json/RNSharePackage.java
Hi,
Due to https://github.com/facebook/react-native/commit/ce6fb337a146e6f261f2afb564aa19363774a7a8 's breaking change, we should remove the override notation of deprecated method `createJSModules`.
Thank you.
> Removed override notation of deprecated method (createJSModules) of React Native 0.47.0

- android/src/main/java/cl/json/social/TwitterShare.java
twitter's package name has changed from `com.twitter` to `com.twitter.android` on android. Updating the package name in source accordingly. Resolves #96
> updating twitter package

- android/src/main/java/cl/json/social/ShareIntent.java
When open the share dialog, the default title is "Share". This a quick fix to able to change the default title.
> Fix share dialog title missing in android

- android/src/main/java/cl/json/social/ShareIntent.java
My case was that I was sharing a PDF and the list would show only apps like "WhatsApp", "Gmail", etc and I needed to also show PDF viewers as "Acrobat Reader".
I added the option `showAppsToView` which is Android-only (I didn't need for iOS) that shows apps that can open/view the file being shared and can be triggered like this:
```js
Share.open({
url: '/path/to/pdf',
type: 'application/pdf',
showAppsToView: true,
});
```
> [Android] Add functionality to show apps that can view a file

- README.md
Sharing base64 image fails on android API 23 and higher if permissions has not been requested.
This seems to affect a number of user : 
- https://github.com/react-native-community/react-native-share/issues/142
- https://github.com/react-native-community/react-native-share/issues/236
- https://github.com/react-native-community/react-native-share/issues/233
- https://github.com/react-native-community/react-native-share/issues/184
I added a step in the android installation step by step, hoping that it will save others some time :)
> updating README - adding android permission request section

- ios/WhatsAppShare.m
The original link isn't resolving, so changed to a non-locale-specific iTunes URL.
While I was there, changed HTTP -> HTTPS.
> Fix broken link to WhatsApp in the iTunes store.

- README.md
- index.js
New optional param for `Share.open` method to cause promise to resolve on user cancel action, rather than rejecting.
This only affects iOS. On android this module already does not reject if user cancels, although there appear to be a couple of requests for supporting that functionality.
Resolves #245
> Allow specifying reject/resolve for user cancel action for sharing on iOS

- README.md
- android/build.gradle
- android/gradle/wrapper/gradle-wrapper.properties
- android/src/main/AndroidManifest.xml
- android/src/main/java/cl/json/RNShareModule.java
- index.js
- package.json
Handling of android permissions in case of sdk version greater than 22. It is handled by checking if the sharing options contains url(s) and if they do and they are base64 strings, then check for write storage permission and proceed accordingly. If the permission is denied, then the share is rejected with 'Permission denied' error.  
Also gradle tools version is made generic to tackle errors in projects using gradle version lesser than this library.
> Permission handling for android in case of base64 sharing

- android/build.gradle
Fixes #386 where jcenter had a POM but 404d the artifact, breaking builds,
while google has the POM and artifact (as it's a google support library)
Also, jcenter is a superset of mavenCentral, so mavenCentral is
redundant:
https://jfrog.com/knowledge-base/why-should-i-use-jcenter-over-maven-central/
> build: reverse dep order, google then jcenter

- README.md
- android/src/main/java/cl/json/social/SingleShareIntent.java
- circle.yml
This pull request resolves Android workflow issue with some social medias singleShare.
User share an image to instagram and see this 
1. user clicks Always and share to Instagram Feed
2. User shares again, and the app opens Instagram Feed by default 
User is not being able to share to Instagram Story anymore, as Android remember decision.
On Android I suggest option **forceDialog**, which disables buttons Always / Just once. Instead, it always forces to choose the option. It looks as attached below.
> SingleShare forceDialog option

- README.md
There was a bug in the instructions for implementing share for android, it was just a duplicate line.
> fixed ReadME typo for android

- index.js
Fixing some flowTypes on isPackageInstalled function promise and packageName param.
Clone the PR, and call the isPackageInstalled function.
> Fixing some flow types on index.js on isPackageInstalled function

- android/src/main/java/cl/json/social/SMSShare.java
In my Android phone, the sms share is not functional.
So I use `android.provider.Telephony.Sms.getDefaultSmsPackage` to get system provider package name.
when android use `Share.shareSingle` with sms, will correctly work.  ( call to internal sms app ).
> fix android sms share default app issue

- ios/GenericShare.h
- ios/GenericShare.m
- ios/InstagramShare.h
- ios/InstagramShare.m
- ios/RNShare.m
* Fix for Facebook and Twitter shareSingle is not working on iOS 11.
* Handled the image share option on Instagram.
> Facebook, Twitter and Instagram shareSingle - Fix on iOS 11

- example/package.json
- example/yarn.lock
This was originally part of the #567 PR but part of the dependencies there were backed down on review so that our example would more closely match the stock react-native 0.60.5 template.
That's not a bad direction to go but the jest dependency specifically needs to move in order to fix security alerts, so I propose this small change to do so
And now finally, hopefully, my github weekly security alert email is empty ;-)
> fix: update jest to fix known security vulnerabilities

- README.md
- android/src/main/java/cl/json/social/ShareIntent.java
- example/App.js
- ios/EmailShare.m
Support sending an email to a predefined email address.
It is based on PR #138 and PR #67, fixes issue #487.
> Send email to predefined email address

- ios/RNShare.m
Fixes #583.
Currently on iOS 13 the app will crash if you:
- Open the share sheet
- Tap something like messages or photos
- Cancel the dialog
- Perform any other action
This is because `shareController.completionWithItemsHandler` is called when the dialog box is canceled and currently `failureCallback` or `successCallback` will always be called. In the situation above, `activityError` is `nil` so `successCallback` will be called even though `completed` is false. This leaves us in a state where the callback has been invoked but the ShareSheet is still active, meaning the success or error callback will be invoked again, leading to the crash.
This PR adds a check to make sure `completed` is true before calling `successCallback`. This way `successCallback` will only be called when the user …
> Only call successCallback when completed is true (iOS 13 crash)

- ios/RNShare.m
Fixes #601.
This PR fixes an issue on iOS 13 where the ShareSheet's promise isn't resolved if the user closes the sheet without completing any actions introduced in #584.
This PR changes the `if (completed)` check in `completionWithItemsHandler` to `if (completed || activityType == nil)`
It looks like in `completionWithItemsHandler` the activityType will only be `nil` if the user closed the ShareSheet themselves, like so:
Here's when they close the reminders modal:
And the photos modal:
This should fix the current issue without reintroducing the crash.
- Ensure promise is resolved when the ShareSheet is closed manually
- Ensure the promise is **not** resolved when a different modal is dismissed (photos, add to contact, reminders, etc)
> iOS 13: Resolve promise if ShareSheet is manually dismissed

- RNShare.podspec
The tags are being named with a "v" and as such, the podspec needs to resolve the tags by including the "v" in the `source` field
Without this fix, users are unable to link the library via CocoaPods. The Cocoapods install fails because it is unable to resolve the `source` of the pod.
> fix: added missing "v" to `source` field in podspec

- components/Overlay.js
- components/Sheet.js
Just noticed another flow issue when running flow in our codebase. Eventually useNativeDriver is a non-optional field https://github.com/facebook/react-native/commit/d123bea8c1a4f1c977928fa2cfffe19132f74dab
so may as well fix this up now.
Run flow!
> Set useNativeDriver explicitly for Animations

- .gitignore
- .npmignore
- android/.npmignore
- android/build.gradle
- ios/.npmignore
- package.json
This wraps the Android Gradle plugin dependency in the `buildscripts` section of `android/build.gradle` in a conditional:
```
if (project == rootProject) {
// ... (dependency here)
}
```
A small change with a big impact: 
The Android Gradle plugin is _only_ required when opening the project _stand-alone_, not when it is _included as a dependency_. By doing this, the project opens correctly in Android Studio, and it can also be consumed as a native module dependency from an application project **without** affecting the app project (avoiding unnecessary downloads/conflicts/etc).
Similarly, the Gradle wrapper (and related scripts) are only required for stand-alone editing/building of the `android` folder. It should _not_ be distributed. Android Studio will automatically generate a wrapper, …
> Update and fix Gradle setup

- README.md
As per request from here: https://github.com/react-native-community/react-native-share/issues/320
@jgcmarins
To make it possible to share directly to other apps, users need to specify queries schemes in LSApplicationQueriesSchemes in their Info.plist files. I've made README more explicit about that.
No code was changed.
> Add some info about iOS installation to README

- components/Button.js
- example/__tests__/__snapshots__/Failed.test.js.snap
- example/ios/Podfile.lock
- example/package.json
- example/yarn.lock
- package.json
- yarn.lock
This updates the `react-native` dependency in the `example` project to the latest version `0.61.5`, as well as aligns other directly related dependencies.
It also updates the `devDependency` in the root project to `0.61.5` (there was one Lint error that was also fixed along the way). `yarn validate` passes successfully now.
> Update react-native to 0.61.5

- example/metro.config.js
The CI is currently failing with
```
> Process 'command 'npx'' finished with non-zero exit value 137
```
The error can be fixed with the proposed change to set `maxWorkers` to `2` in the metro config for the example project. While it would be nice to set this value on _CI only_, I have not found a different/better way to do it.
> Set maxWorkers to 2 for example project

- ios/RNShare.m
Package keep crashing app in DEV mode when user cancel and open "Save to files" option on iOS. 
Solution is to hide action sheet on activityError to prevent callbacks to be called numerous times.
Related issue: https://github.com/react-native-community/react-native-share/issues/659
1. Open action sheet.
2. Choose Save to files option and cancel. 
3. Repeat second point
4. Now whole action sheet should hide
> iOS: Hide view controller on activityError

- README.md
- ios/WhatsAppShare.m
Currently, sending texts to a whatsAppNumber is not supported on iOS, this pull request proposes to mitigate this issue.
Tested in my iPhone XR.
> Enables sending text via WhatsApp on iOS to a specific phone number.

- android/src/main/java/cl/json/RNSharePathUtil.java
- android/src/main/res/xml/share_download_paths.xml
Currently the Android config does not support sharing of files from secondary storage (sd cards). Developers/users have used the base64 workaround for this, but I thought it would be a good idea to support it.
Also none of these would solve it:
```
<external-files-path
name="external_files"
path="." />
<external-cache-path
name="external_cache"
path="." />
<files-path
name="files"
path="." />
```
On an emulator or device, download an image to the sdcard or "external storage" and then share it.
> Support sharing of files from secondary storage i.e sd cards, on Android

- README.md
- index.js
- ios/FacebookStories.h
- ios/FacebookStories.m
- ios/RNShare.m
- ios/RNShare.xcodeproj/project.pbxproj
Implement Facebook Stories share.
Follow this document of Facebook: https://developers.facebook.com/docs/sharing/sharing-to-stories/ios-developers
- Add more handler for share to Facebook.
- Tested with my React Native project on iPhone 7.
> feat: Implement Facebook stories share

- index.js
In Android this behaviour would result in `Intent.ACTION_SEND_MULTIPLE` instead of `Intent.ACTION_SEND` for a single file. Some apps could support one, but not another.
I've checked in on a real device using https://f-droid.org/en/packages/de.k3b.android.intentintercept/
> Only convert options.url to options.urls in iOS

- package.json
- yarn.lock
Small update to align the `react` dependency with `react-native`.
Fixes
```
warning " > react-native@0.62.2" has incorrect peer dependency "react@16.11.0".
```
> Set react peer dep to 16.11.0

- .circleci/config.yml
- example/android/app/build.gradle
This PR changes the basic config at `circle.yml`  to use [react-native-orb](https://circleci.com/orbs/registry/orb/react-native-community/react-native) directly. Leading to a an abstraction of some commands like `android build`, etc.
Check if the CI still working without problems 👯
> Changing CircleCI config to use react-native orb

- android/src/main/java/cl/json/social/ShareIntent.java
- example/App.js
- index.js
- website/docs/share-open.mdx
- website/docs/share-single.mdx
Add an optional field `recipient` for SMS destination recipient, resolves #812.
When choosing to share using SMS, you can include one recipient as a string. For example: 
```js
Share.shareSingle({
title: 'Hello SMS!',
social: Share.Social.SMS,
recipient: '123-4567890',
message: 'Example SMS message',
});
```
Different vendors have different formatting when specifying multiple destination phone numbers. And also, some vendors do not even support adding multiple destination phone numbers when using the `ACTION_SEND` intent. Which would require the `ACTION_SENDTO` intent. However, could be implemented in the future.
Test it through the example app.
> feat: adding recipient for sms on Android

- website/docs/share-single.mdx
This PR aims to update the docs in order to accurately reflect the steps needed to take in order to actively use the Share.singleShare method.
Previously, the docs noted that the method to use was simply `share`. This was causing console warnings that were resolved when checking the source code for a matching method and noticing that one did not exist.
The decision to make this PR was in order to prevent confusion over the current documentation
> Update share-single Documentation

- example/ios/example/Info.plist
This PR aims to clarify the issues faced when trying to implement singleShare for facebook. More specifically, specifying `facebook` in the `Info.plist` does not necessitate the ability to share on facebook since the matching string is `fb`.
By updating the `example/Info.plist`, users will be able to accurately understand what is needed in order to integrate facebook sharing functionality.
This should help provide an answer to the issues faced here:
https://github.com/react-native-community/react-native-share/issues/384
Updating the `Info.plist` to accurately reflect the facebook string expected in order to improve documentation and allow for facebook sharing
> Update Info.plist in Examples

- android/src/main/java/cl/json/ShareFile.java
- android/src/main/java/cl/json/social/ShareIntent.java
- android/src/main/java/cl/json/social/SingleShareIntent.java
There were a couple of shortcomings when trying to share Instagram Stories on Android. `base64` would _not_ work on a file of any decent size. The flags on the intents were not set correctly, so Instagram was not able to open the image after it was sent. Stickers could only be sent if you were using `forceDialog`.
I've just upstreamed the changes I made at work to get Instagram Stories to work in our app.
Fixes #852 
Fixes #853 
Fixes #854 
Fixes #855
There are no tests for Android currently. I have patched these changes into the app at work, and they all work as expected (for us), so I'm upstreaming them
> Fixes for some bugs with Instagram Stories on Android

- RNShare.podspec
Latest Xcode 12 fails to build while without a module to depend on `React-Core` directly hence this change is necessary for all native modules on iOS. For more details please check: https://github.com/facebook/react-native/issues/29633#issuecomment-694187116
Use this branch to install with an app running on Xcode 12.
> fix: Xcode 12 compatibility

- android/src/main/java/cl/json/social/ShareIntent.java
When try to share a file or message via WhatsApp with no number receive a error:
```js
Share.shareSingle({
title: 'Foo',
url: 'path/to/my/file',
social: Share.Social.WHATSAPP,
});
```
Error:
```java
com.facebook.react.bridge.NoSuchKeyException: whatsAppNumber
at com.facebook.react.bridge.ReadableNativeMap.getNullableValue(ReadableNativeMap.java:122)
at com.facebook.react.bridge.ReadableNativeMap.getNullableValue(ReadableNativeMap.java:126)
at com.facebook.react.bridge.ReadableNativeMap.getString(ReadableNativeMap.java:161)
at cl.json.social.ShareIntent.open(ShareIntent.java:132)
at cl.json.social.SingleShareIntent.open(SingleShareIntent.java:40)
at cl.json.social.WhatsAppShare.open(WhatsAppShare.java:21)
at cl.json.RNShareModule.shareSingle(RNShareModule.java:158)
at …
```
> Check if whatsAppNumber key exists before get it

- index.js
The `Platform.constants` added in #871 is not available in RN versions before 0.61 as reported in #879. `Platform.Version` is still there, and it's documented so I've switched to that instead.
Going to ask @alemarra89 if they can install this branch and test that it resolve the issue.
> fix: use documented Platform.version for backwards compat

- index.js
A recent change to the repo has caused Flowtype check to fail.
`Platform.Version` returns a `string`, and cannot be directly compared to a number.
- Run Flowtype check
- Confirm that the type checking passes
> Fix Flowtype error

- android/src/main/java/cl/json/social/ShareIntent.java
Background video assets currently is only available for iOS, this PR aims to add support for Android as well.
- Fixes #907 
<details>
<summary>Minimal example</summary>
```js
import React from 'react';
import {StyleSheet, View, Button} from 'react-native';
import RNFetchBlob from 'rn-fetch-blob';
import Share from 'react-native-share';
const App = () => {
const share = async () => {
try {
const cache = await RNFetchBlob.config({
fileCache: true,
appendExt: 'mp4',
}).fetch('GET', 'https://www.w3schools.com/html/mov_bbb.mp4');
await Share.shareSingle({
social: Share.Social.INSTAGRAM_STORIES,
method: Share.InstagramStories.SHARE_BACKGROUND_VIDEO,
backgroundVideo: `file://${cache.path()}`,
});
} catch (error) {
console.error(error);
}
};
return (
<View style={styles.container}>
<Button …
```
> feat (android): add support to Instagram Stories video sharing

- android/src/main/AndroidManifest.xml
- example/android/app/src/main/AndroidManifest.xml
- website/docs/installing.mdx
- website/docs/migrate-v4-to-v5.mdx
- website/docs/share-open.mdx
- website/sidebars.js
- yarn.lock
Fixes proposal https://github.com/react-native-share/react-native-share/issues/936.
I've removed the `WRITE_EXTERNAL_STORAGE` permission from the module's AndroidManifest.xml file (and added this to the example project), as it should be the responsibility of the implementing project to add this permission if base64 file sharing is a requirement. I have also updated the documentation to mention this change.
As detailed on the issue, I see this as a breaking change (to prevent the possibility of implementing projects picking a new version with this included, and apps breaking unexpectedly), so I have included additional migration documentation too.
Please let me know if there's any changes required!
Upon opening the example project, it should be possible to share base64 files, in the same …
> Proposal: Removal of WRITE_EXTERNAL_STORAGE permission

- index.js
The `appId` option isn't mentioned in the [docs](https://react-native-share.github.io/react-native-share/docs/share-open/#supported-options) but is marked as mandatory in the Options flow type which breaks flow type checking.
> Make appId optional in Options type

- ios/RNShare.m
The `Share.open` promise doesn't resolve in some situations on iOS. For example when you cancel printing. It's well described in #865. This PR fixes that.
Fix #865 #857
Please check #865, there are steps for reproduce and it should work as expected with this fix.
> fix: resolve promise on ios every time

- android/src/main/java/cl/json/social/ShareIntent.java
This is a follow-up to my previous PR https://github.com/react-native-share/react-native-share/pull/968 - looks like I have introduced a bug there.
According to the [official dev guide](https://developer.android.com/training/sharing/send.html#send-binary-content) we only need to set the type, and the URI goes to `EXTRA_STREAM`.
Without this change if I share a file to, say Gmail, I get a new email with the subject containing the URI which is clearly wrong. After the fix, as expected, I get a new email with the file attached.
Fixes https://github.com/react-native-share/react-native-share/issues/976
> Android: fix sharing a single file

- index.js
With `exact_by_default=true` we get flow errors because `OpenReturn` and `ShareSingleReturn` are implicitly inexact. This PR marks them explicitly inexact.
> Mark OpenReturn and ShareSingleReturn flow types as inexact

- ios/RNShare.m
This PR fixes for https://github.com/react-native-share/react-native-share/issues/981 "If the Share dialog is opened from a Modal, even Modal is getting dismissed when we close share dialog".
> "If the Share dialog is opened from a Modal, even Modal is getting dismissed when we close share dialog" - Issue Fix

- website/docs/share-open.mdx
- website/docs/share-single.mdx
As someone who is new to the library, I struggled to understand what the open() and shareSingle() methods do and the difference between them. I think adding these short descriptions to the docs may help others in the same position.
> Added a quick summary of the open() and shareSingle() methods to docs

- ios/WhatsAppShare.m
This PR fix bug [#603](https://github.com/react-native-share/react-native-share/issues/603). With this implementation the _Share.shareSingle_ method will share an Image with Whatsapp.
As described in iOS [Whatsapp Documentation](https://faq.whatsapp.com/iphone/how-to-link-to-whatsapp-from-a-different-app/?lang=en) is not possible to share an image with Custom URL and text with image at the same time with Document Interaction API.
1. Install Whatsapp on iOS device and verify the account.
2. Open your app
3. Invoke the _Share.shareSingle_ method with these options
```
{
title: "title",
subject: "subject",
url: data:image/jpeg;base64,${base64},
social: Share.Social.WHATSAPP,
message: "message"
}
```
4. iOS Document Interaction will open;
5. Choose Whatsapp;
6. A preview of image will open on …
> fix(whatsapp): fix iOS Whatsapp images share

- android/src/main/java/cl/json/social/TargetChosenReceiver.java
Google Play rejects apps using this library because of an Implicit PendingIntent Vulnerability: https://support.google.com/faqs/answer/10437428
This PR should fix #1043
Verified that the sharing functionality works in my Android app with this fix
> fix(android): prevent implicit PendingIntent vulnerability

- ios/EmailShare.m
Adding URL parameter in `shareSingle` method for `social` type `EMAIL`
https://github.com/react-native-share/react-native-share/issues/932
Tested on iPhone before and after change
https://www.loom.com/share/d41d13e935774e4190fd44ab731d544d
> Fix iOS Email URL sharing bug

- _config.yml
- website/docs/installing.mdx
I could not use `Share.shareSingle()` in Android 11 (Ever open the Google Play) then searching I see that Android 11 implements changes related to package visibility of others app.
My PR is implement documentation for others developers don't spend time searching a solution!
My closed issue about this is #1052 
If need read more about the changes [click here](https://developer.android.com/training/package-visibility)
> Implement new step in documentation for Android SDK  30+

- android/src/main/java/cl/json/RNShareModule.java
- android/src/main/java/cl/json/social/TelegramShare.java
- src/index.tsx
- src/types.ts
- src/typings/react-native.d.ts
- website/docs/share-single.mdx
> added single share feature for telegram

- src/types.ts
Hi,
This change allows those depending on your package to supply only the necessary fields when using the ShareOptions type. Currently developers are needing to supply a much larger than needed object to have a valid ShareOptions type (or code that references ActivityItemSource). 
Fields that are not classed as optional are still needed.
Before:
```
{
url,
title,
activityItemSources: [
{
placeholderItem: { type: 'text', content: url },
item: {
addToReadingList: undefined,
airDrop: undefined,
assignToContact: undefined,
copyToPasteBoard: undefined,
mail: undefined,
message: undefined,
openInIBooks: undefined,
postToFacebook: undefined,
postToFlickr: undefined,
postToTencentWeibo: undefined,
postToVimeo: undefined,
postToWeibo: undefined,
print: undefined,
saveToCameraRoll: undefined, …
```
> Add Optional Types to ActivityItemSource

- android/src/main/java/cl/json/social/TargetChosenReceiver.java
https://github.com/react-native-share/react-native-share/issues/1073 describes the issue.
Ref: Android 12 behavior changes https://developer.android.com/about/versions/12/behavior-changes-12#pending-intent-mutability
Apply the fix, and the project which targets Android 30 can successfully call `Share.open` without throwing.
> Specify PendingIntent.FLAG_IMMUTABLE for Android S+

- android/src/main/java/cl/json/RNShareModule.java
Before this change, the Promise returned by calling `Share.open()` on Android would not resolve after a successful share, only if sharing was cancelled. Therefore, clients of the library could not handle completion of sharing, such as by removing a loading indicator. With this change, `Share.open()` on Android properly calls the success callback and resolves the Promise.
Tested with our app's usage of react-native-share. Before this change, on Android, the Promise returned from `Share.open()` would not resolve after sharing the content, and so we wouldn't run the following line of code updating our `loading` state to `false`. With this change, `await Share.open(...)` would complete, the following line of code updating the `loading` state would run, and the loading indicator would be …
> Resolve Promise on successful share for Android

- RNShare.podspec
Since `LinkPresentation` API is only available on iOS 13 and above, we need to mark the `LinkPresentaion` as a weak framework. Else, there will be a startup crash on iOS 12 instead of a build error `dyld: Library not loaded: /System/Library/Frameworks/LinkPresentation.framework/LinkPresentation`. 
Fixes #1095 
Build the app on iOS 12 device, before the fix the app will crash on startup. And the app should work normally after the fix.
> Set `LinkPresentation` as weak framwork on IOS

- .circleci/config.yml
- android/src/main/java/cl/json/RNSharePathUtil.java
- android/src/main/java/cl/json/ShareFile.java
- android/src/main/java/cl/json/ShareFiles.java
- android/src/main/java/cl/json/social/FacebookStoriesShare.java
- android/src/main/java/cl/json/social/InstagramStoriesShare.java
- android/src/main/java/cl/json/social/ShareIntent.java
- website/docs/share-open.mdx
- website/docs/share-single.mdx
Hey hey !
We've noticed that this library is using `getExternalCacheDir`, which usually returns `/sdcard/Android/data/com.package.name/cache`. The thing is, on Android <= 10, this directory can be accessed by any application that has the `WRITE_EXTERNAL_STORAGE` permission, and this can basically lead to any malicious application accessing the previous files you shared. In our case, we share sensitive information, and we don't want them to leak.
I added a `useInternalStorage` option that is replacing it by `getCacheDir` which returns `/data/data/com.package.name/cache`, that can only be accessed by the application with the `com.package.name` identifier.
I tested it locally and it works fine. My flow was:
- Share a file
- Check that `/sdcard/Android/data/com.package.name/cache` is still …
> feat(android): add  `useInternalStorage` share option to avoid external storage

- android/src/main/java/cl/json/social/InstagramShare.java
- website/docs/share-single.mdx
Sharing to Instagram using `shareSingle` and the `social` property `Social.Instagram` opens an intent chooser that lets the user decide between sharing as Instagram Direct, Feed, or Stories. Direct and Feed are working but Stories doesn't.
The issue looks similar to [this one](https://github.com/react-native-share/react-native-share/issues/1084)
For sharing as Stories, instead of using the Android intent action `ACTION_SEND`, one needs to use the action ` "com.instagram.share.ADD_TO_STORY"` as in the Instagram documentation [example](https://developers.facebook.com/docs/instagram/sharing-to-stories).
To fix the issue - and only for image data - we create a chooser intent that combines the `ACTION_SEND` intent and the Instagram `ADD_TO_STORY`  intent as extra initial intent. The approach …
> fix(instagram): fix black screen issue for instagram stories with Social.Instagram

- ios/GenericShare.m
- website/docs/troubleshooting-ios.mdx
As Twitter removed the support for the development kit, there is an issue in the visualization of a post. Related to https://github.com/react-native-share/react-native-share/issues/930
Share a tweet using the library, this will open the browser, and if the phone has the app, then the Twitter app will be launched correctly.
> Remove twitter native support on iOS

- android/src/main/java/cl/json/social/InstagramStoriesShare.java
Solution found by https://github.com/marf on this thread https://github.com/react-native-share/react-native-share/issues/1084#issuecomment-932348328
Kia ora! Currently on the android side of the library, when sharing to an instagram story your image won't appear, and instead you'll see a blackscreen. @marf found a solution, and I've implemented it here. 
There was another PR which aimed to fix this issue https://github.com/react-native-share/react-native-share/pull/1126
However it only updated the `InstagramShare.java`, not the `InstagramStoriesShare.java`, hence this PR.
Use the `Share.shareSingle` function with the Instagram stories prop, along with a background image.
e.g. `await Share.shareSingle({social: Share.Social.INSTAGRAM_STORIES,
backgroundImage: image})`
Before this fix you'll …
> Fixed android instagram stories black screen

- android/src/main/java/cl/json/social/WhatsAppBusinessShare.java
- android/src/main/java/cl/json/social/WhatsAppShare.java
Workaround for the issue https://github.com/react-native-share/react-native-share/issues/952 . Images were not being shared to a specific number if the conversation was never opened before. The workaround found is to open a blank conversation first, then trying to share it again.
On the App.js from example app, change the `shareSingleImage` function to the following:
```javascript
/**
* This functions share a image passed using the
* url param
*/
const shareSingleImage = async () => {
const shareOptions = {
title: 'Share file',
url: images.image1,
failOnCancel: false,
social: 'whatsapp',
whatsAppNumber:
'Insert a number never contacted before here. Must include the country code, and not include symbols.',
};
try {
const ShareResponse = await Share.shareSingle(shareOptions); // change it …
```
> fix: support unknown whatsapp number

- android/src/main/java/cl/json/RNShareModule.java
Not setting locale for language/country neutral operation may cause bug depending on the default locale.
See https://docs.oracle.com/javase/7/docs/api/java/util/Locale.html#ROOT
Note: I am just searching for toLowerCase() and toUppercase() in my project's dependencies and send the same PR, in order to potentially raise the awareness. Although I've seen the lack of explicit locale has caused issues for us, I am not sure if react-native-share is actually affected.
Example related issue: joltup/rn-fetch-blob#573
> Use root locale when changing case in java

- ios/RNShareActivityItemSource.m
The title which user has provided in the linkMetaData options should not be overwritten by metadata from url, unless title is not specified by the user.
Test Case 1:
Pass the title prop in LinkMetaData options, while sharing the title passed should be present even if the title in metadata is different.
Test Case 2:
If title is not specified in the LinkMetaData options, while sharing the title must be taken from metadata in URL
> fix(ios): custom title got over written by meta data

- ios/RNShare.m
[initWithURLs:inMode](https://developer.apple.com/documentation/uikit/uidocumentpickerviewcontroller/2921628-initwithurls?language=objc)  deprecated on iOS 15+. Use [initForExportingURLs](https://developer.apple.com/documentation/uikit/uidocumentpickerviewcontroller/3566731-initforexportingurls?language=objc) instead on iOS 15+.
**Device Test:**
iOS15+:
Mac Catalyst:
> fix(ios): Replace initWithURLs with initForExportingURLs on iOS 15+

- ios/FacebookStories.m
- ios/InstagramStories.m
- ios/WhatsAppShare.m
simple change to the URL schema of Facebook, Instagram, and Whatsapp
Manually tested on **Pixel_4_API_30 simulator**.
_PS: No physical iPhone to test on_
> fix(ios): use https in place of https for facebook/instagram/whatsapp

- .circleci/config.yml
their default is still 12, semantic release requires 16
Not sure exactly how to test this - hopefully CircleCI runs it when I propose this change?
It'd built directly from docs here:
https://circleci.com/developer/orbs/orb/react-native-community/react-native
> build(deps): use node v16 in circleci config

- .circleci/config.yml
This should fix the MacOs build error. Enabling us to merge #1217
I hope CircleCI will build and everything is going to pass. 😅
> ci(mac): setting default node version to 16

- .circleci/config.yml
Setting node version to 14, in order to properly publish new packages due to #1217 bumping semantic-release
Run at CircleCI 🚀
> ci(node): setting publish version to 14

- website/docs/share-package-installed.mdx
Cross-link installation step to  add queries for Android in isPackageInstalled docs page
ran the docs website locally and verified the change
> add instruction to check instalation docs

- android/src/main/java/cl/json/social/FacebookStoriesShare.java
As said in [this issue](https://github.com/react-native-share/react-native-share/issues/1196), Facebook Stories is not working on Android, @steo-ml shows a fix [here](https://github.com/react-native-share/react-native-share/issues/1196#issuecomment-1120639001).
The image in Facebook Stories is using `ShareFile` constructor without the image type, some problem is happening to get the image type (probably a future fix on `ShareFile`), and the temporary fix is to use the constructor which you can send the type.
Run Android app, and try to share Facebook Stories using a background image or sticker image
> fix(android): facebook stories

- src/types.ts
fix #1241 (excludedActivityTypes allow specific android package names but TypeScript interface don't)
https://github.com/react-native-share/react-native-share/blob/3038dd4d3b315eaad08e259528ce176a0afa85bd/android/src/main/java/cl/json/social/ShareIntent.java#L62
> Change type of excludedActivityTypes

- android/src/main/java/cl/json/social/InstagramStoriesShare.java
While sharing an Instagram story with **backgroundVideo** option, iOS works fine with remote urls. But on Android you have to download and cache it, then use the local file path to pass IG. But currently it doesn't work, because we're giving file type "image/jpeg" in every scenario.
I've changed the type according to if statement that already exists. And default type is still "image/jpeg".
I tested the fix on Samsung S7(Android 8.0-API-26).
I'm already using the fix with [patch-package](https://www.npmjs.com/package/patch-package) and I'm adding the changes here so you can use and test it right away:
**react-native-share+7.6.4.patch**
```
diff --git a/node_modules/react-native-share/android/src/main/java/cl/json/social/InstagramStoriesShare.java …
```
> fix(android): add background type for instagram video story sharing

- example/App.js
- example/ios/Podfile.lock
- ios/EmailShare.m
- ios/FacebookStories.m
- ios/GenericShare.m
- ios/GooglePlusShare.m
- ios/InstagramShare.m
- ios/InstagramStories.m
- ios/TelegramShare.m
- ios/ViberShare.m
- ios/WhatsAppShare.m
- src/index.tsx
I made a few changes to improve iOS code and the Example project.
- On iOS the usage of `successCallback` was sending parameters empty, so, on JS code the result of `status` and `message` get `undefined`, I added a `true` boolean and a empty message just to avoid `undefined`.
- When sharing Facebook Stories, Instagram Stories or Google Plus, you did't get a error if the user not have the application installed, it was just opening the App Store, now we have a `failureCallback` (the code was there but not used).
- I have added two more examples to Google Plus and WhatsApp, and the result of each share too. 
- I added a `Boolean` convertion on response from `shareSingle` because the status was getting `1` and not `true`
- I updated the version of `RNShare` on `Podfile`to the latest too. 
- …
> fix(ios): successCallback usages

- ios/MessengerShare.h
- ios/MessengerShare.m
- ios/RNShare.m
- ios/RNShare.xcodeproj/project.pbxproj
- ios/RNShareUtils.h
- ios/WhatsAppShare.m
- website/docs/share-single.mdx
Add a feature to share URLs for Messenger on iOS
I want to port this implementation into this repo.
```js
Linking.openURL('fb-messenger://share?link=https://github.com/react-native-share/react-native-share');
```
ref: https://tools.applemediaservices.com/app/454638411?country=us
> feat(ios): Share a link for Messenger on iOS

- website/docs/share-single.mdx
As the title states, this small doc change would have saved me from the issue I raised in https://github.com/react-native-share/react-native-share/issues/1291
Totally flexible about the wording or arrangement, I think it's just important to mention somewhere in the docs that closing the sheet throws an error.
No code changes, just a documentation improvement :)
> Document that error is thrown when sheet is closed

- ios/GenericShare.m
With this PR, Twitter shareSingle with image works on iOS.
Without this, shareSingle will copy the image url as a string in the Twitter card message.
> Fixed Twitter shareSingle with image on iOS

- ios/RNShareActivityItemSource.m
- src/types.ts
A few applications' api do not allow for sending of both messages and url (E.g.: #280 #760 WhatsApp, Slack). When this happens, the app api randomly chooses either the message or the url to be shared to the application (for WhatsApp, the message is always prioritized over the url). We would like to specify which of the two to send for these type of application when calling Share.open using activityItemSources.
Inside where I am calling Share.open, I can now specify the bundle to specifically tell share options what to send and what not to, instead of just using the default ActivityTypes.
```ts
const url = payload.url ?? '';
const message = payload.message ?? '';
const options: ShareOptions = Platform.select({
ios: {
activityItemSources: [
{
placeholderItem: { type: 'url', content: url }, …
```
> Allow custom activity types to be specified inside activityItemSources

- android/src/main/java/cl/json/social/InstagramShare.java
- example/App.js
Hi there,
We are using your library at our company, however we had problems sharing direct messages on instagram with android.
The current behaviour is that nothing happens if a url is not provided, and when provided it says that the file type is not supported. 
This patch tries to fix that by passing `text/*` as type in the options.
In the example app simply try to send an instagram direct message.
Cheers
> fix(android): instagram direct share plain text

- website/docs/installing.mdx
Quick documentation change to make it more readable
Change: 
Doc changes Provided an example for the Android queries tag to make documentation clearer. Moved the whole section to the top of the installation guide as most apps will now be on SDK >=30 therefore making it more relevant.
Reason for change: 
I was reading documentation and I have missed the android step, and I thought it could also do with an example for people not used to handling manifests.
I have ran the Docusaurus code locally and it looks fine
> docs: updating docs with examples

- website/docs/share-single.mdx
since jan 2023, facebook requires appId for sharing to stories. adding that to the documentation so people know they need to add it
no need , just updated docs. the code for appId already existed
> fix: add documentation for the newly required appId for ig stories

- RNShare.podspec
This PR fixes `RCT_NEW_ARCH_ENABLED=1 pod install` command on RN <= 0.70.
> fix(ios): folly_compiler_flags missing on RN<=0.70

- android/src/newarch/cl/json/RNShare.java
This PR fixes a compile error on Android with the new architecture. The bug is explained in the following thread I opened: [https://github.com/react-native-share/react-native-share/issues/1415#issue-1790174827](url)
> fix(android): Build fail in New Architecture

- android/src/main/java/cl/json/RNShareImpl.java
`Share.open` is not returning promise in Android.
Callback resolve call added to `RNShareImpl` to close the cycle.
(Might) close #1405 
Help wanted.
> Share.open not returning promise in Android

- example/App.js
- ios/RNShare.mm
- ios/RNShare.xcodeproj/project.pbxproj
- ios/SmsShare.h
- ios/SmsShare.m
- website/docs/share-single.mdx
This PR expands on the work done by @ku8ar https://github.com/react-native-share/react-native-share/pull/1447 and adds:
1. Support for passing url as options 
2. Updates docs
3. Adds iOS Sms shareSingle usage in example app
4. Includes sms in exported constants
Build locally and run the example app. 
**Demo of Exampe App**
https://github.com/react-native-share/react-native-share/assets/20777666/faffe1d1-8620-480f-9553-fc3b8fe5e5d2
**Demo of URL option in our app that uses this library**
https://github.com/react-native-share/react-native-share/assets/20777666/179e1d63-221e-44ff-a55b-fd5c1a20389c
> feat(ios): support sms share

- android/build.gradle
Trivial change to support AGP 8 as mentioned here: https://github.com/react-native-community/discussions-and-proposals/issues/671
Nicola mentioned also we shouldn't remove package attribute from AndroidManifest to not lose compatibility with AGP < 8. I don't think it's worth maintaining logic to remove that attribute contitionally since it will only cause a warning to users on AGP 8 and above. 
ps: [I acknowledged someone else](https://github.com/react-native-share/react-native-share/pull/1401) already tried this change but they remove package attribute which is not ideal.
I did not build this locally since it's a trivial attribute addition.
> feat(android): add namespace to support AGP 8

- ios/RNShare.mm
The messenger share functionality is not working properly due to the typo issue we made here.
The share functionality of Messenger is not working on iOS due to the condition mismatch and have analysed the code and found we made a typo in the constants file. Have fixed it. Kindly review and share feedback.
I did not build this locally since it's trivial.
> fix(ios): fixed typo in RNShare.mm file

- ios/RNShare.h
This fixes an IOS compile error with the new architecture. [1232](https://github.com/react-native-share/react-native-share/issues/1232)
> fix(ios): Build fail in New Architecture

- android/src/main/java/cl/json/RNSharePackage.java
I've been testing Bridgeless mode in 0.74 RC3 and realized that the library is broken on Android. Here the fix
| Before | After |
| ------ | ----- |
| ![untitled2](https://github.com/react-native-share/react-native-share/assets/3001957/07265363-3403-4be9-ae9c-971511c55716) | ![untitled](https://github.com/react-native-share/react-native-share/assets/3001957/30f7bf25-3f86-4130-a5c0-7eb73c7a523f) |
> [Android] Add support for Bridgeless Mode - 0.74

- .circleci/config.yml
CI is currently failing on iOS. I'm not super familiar with this CI setup, but I bumped the orb version to see if that would help. It didn't. It looks like the orb is still configured to use brew casks in a couple places, which will error on recent versions of homebrew. Additionally, we were spending some unnecessary compute minutes installing Android tools on the macOS executor that is only responsible for building for iOS. I also switched to using npm to install Detox, as they recommend in their docs, but this isn't really necessary since the job doesn't actually use Detox.
Let CI run
> chore(ci): Fix failing build-lint-app workflow

- android/src/main/java/cl/json/RNShareImpl.java
- android/src/main/java/cl/json/social/DiscordShare.java
- codegenSpec/NativeRNShare.ts
- example/App.js
- ios/DiscordShare.h
- ios/DiscordShare.m
- ios/RNShare.mm
- src/index.tsx
- src/types.ts
Add discord share for both Android and IOS
Add  share button in example project，there is a video of Android
https://github.com/react-native-share/react-native-share/assets/51528647/732a47df-7643-488d-b9cf-3db9a850eb3b
> feat: support discord share for android and ios

- ios/WhatsAppShare.m
I've been using react-native-share for a while, and as part of my process to dive into native development, I decided to contribute to it. 
I had some difficulty understanding the logic behind the iOS WhastAppShare module, so this PR is a refactoring that applies a few clean code principles to improve the code's readability. 
- Create an ENUM to clarify what kind of data can be processed: Text, Image, and Video. 
- Split specific tasks in meaningful named functions: `tryToSendImage`, `isWhatsAppAvailable`, `getMessageType`, etc.
- Remove duplicated code by encapsulating it in reusable functions: `handleError,` `shareMedia`.
I'm willing to keep working on this kind of refactoring, but before spending more time I want to know if it is something you are interested in. 
I tested the …
> refactor(ios): Improve WhatsAppShare readability

- RNShare.podspec
We at [Software Mansion](https://swmansion.com/) have been working on [improving support](https://blog.swmansion.com/sunrising-new-architecture-in-the-new-expensify-app-729d237a02f5) for the new architecture for quite a while now. If you need help with anything related to New Architecture, like:
- [migrating your library](https://x.com/swmansion/status/1717512089323864275)
- [migrating your app](https://github.com/Expensify/App/pull/13767)
- [investigating issues](https://github.com/facebook/react-native/pulls?q=sort%3Aupdated-desc+is%3Apr+author%3Aj-piasecki+is%3Aopen)
- [improving performance](https://x.com/BBloniarz_/status/1808138585528303977)
or you just want to ask any questions, hit us up on [projects@swmansion.com](mailto:projects@swmansion.com)
---
PR adding proper way of adding …
> fix: use proper way of deciding about new arch in podspec

- ios/RNShareActivityItemSource.m
- website/docs/share-open.mdx
Enhancement to library [react-native-share](https://github.com/react-native-share/react-native-share) to load share icon image from base64.
require usage of changeOption to this format:
```
const shareOptions = Platform.select({
ios: {
activityItemSources: [
{
placeholderItem: {
type: 'text',
content: '...'
},
item: {
type: 'text',
content: '...'
},
linkMetadata: {
title: 'Title M2U Receipt',
base64Icon: `${yourLogo}` <-- Note: pass base64 image data here, image can be converted to base64 and define directly in file. Instead of live conversion.
}
},
],
},
default: {
title: 'Receipt',
},
});
```
> New Feature: add base64 image support under linkMetadata for IOS for custom sharing icon

- ios/InstagramStories.m
I am using this library on project that integrate social media accounts and their functionalitites such as sharing content and I encountered an issues when sharing to instagram story. After investigating the issues I found that there is an issue from the library side and after fixing it locally I wanted to contribute to the community so that I can help others out.
The issue came from this line of code: 
`NSData *video = [NSData dataWithContentsOfURL:backgroundVideoURL];`
It returned nil and the story had no video displayed when it opened the instagram app.
I just modified the code to use PHAsset for retrieving the video data with the provided file_url in an asynchronous way so that larger files can also be supported.
I tested the code using an iOS device, given that the simulators do not …
> Fix: fix large file sharing to instagram stories

- README.md
- app.plugin.js
- package.json
- plugin/src/index.ts
- plugin/tsconfig.json
- website/docs/installing.mdx
- yarn.lock
**Expo** is increasingly used nowadays, and the capability of easy integration could be a game changer for that library.
Here is a pull request which contains:
- Expo config plugin for both iOS and Android
- Documentation update
1. I have built the library thanks to `yarn prepare`
2. Sym-linked thanks to `yarn link` locally
3. And `yarn link react-native-share` on an expo project
4. Added the plugin inside my `app.config.ts` with the queries passed as arguments
5. `yarn prebuild` on my example project to generate `ios` and `android`
6. I can verify that `Info.plist` and `AndroidManifest.xml` have successfully been linked with the different queries passed
> New Feature: Expo support with config plugin

- src/types.ts
This adds `base64Icon` to the `LinkMetadata` interface, as per the [docs](https://react-native-share.github.io/react-native-share/docs/share-open#linkmetadata)
N/A
> fix(types): add base64Icon to LinkMetadata interface

- plugin/src/index.ts
I ran into two edge cases when trying to utilize this package, specifically when using the Expo plugin. First, when running `expo prebuild` within my real project, I received an error `Cannot read properties of undefined (reading 'ios')`.
Upon investigation, the error appeared to be occurring because the `props` parameter was undefined.
To further diagnose I created a minimal repo, only to run into another error upon prebuild, `TypeError: config.ios.infoPlist.LSApplicationQueriesSchemes is not iterable`.
I added some logging just inside my node_modules folder and discovered that LSApplicationQueriesSchemes was being provided as an object in my case (I'm not sure why this is occurring exactly, it's listed as an array within the Info.plist file).
To fix this, I added a function which checks …
> fix(ios): handle for edge case in Expo plugin when LSApplicationQueriesSchemes is an object and props are undefined

- src/components/ShareSheet.tsx
Since RN 0.77 removeEventListener no longer exists on BackHandler, causing type errors. Updated ShareSheet to use new method of removing the subscription. More information can be found here: https://reactnative.dev/blog/2025/01/21/version-0.77#android
Verified within my own production app that it now builds and doesn't cause type errors
> fix: handle RN 0.77 breaking change for event listener unsubscribe

- ios/GenericShare.m
Sharing to Facebook is not supported on iOS and will always open a web browser.
Check: https://github.com/react-native-share/react-native-share/issues/1657, https://github.com/react-native-share/react-native-share/issues/1535, and https://github.com/react-native-share/react-native-share/pull/1315#issuecomment-1548745717.
Looking at the code, sharing on Facebook uses the [GenericShare](https://github.com/react-native-share/react-native-share/blob/main/ios/GenericShare.m) on iOS, which always throws an error and opens a web browser as it [only supports Twitter](https://github.com/react-native-share/react-native-share/pull/1315).
Instead, we should show the share sheet for any app if the provided URL can be opened, or at least be explicit about the apps we support …
> fix(ios): update shareSingle method to check if inAppBaseUrl can be opened instead of checking only for Twitter

- android/src/main/res/xml/share_download_paths.xml
This PR removes the use of `<root-path>` from the `FileProvider` configuration. It was originally added in [PR #754](https://github.com/react-native-share/react-native-share/pull/754) to support SD card sharing, but it's considered unsafe and creates security issues for the apps using this library.
Using `<root-path path="."/>` exposes too much. Apps should explicitly define safer paths like `cache-path` or `files-path` to avoid unintentionally sharing sensitive data.
Per [Android docs](https://developer.android.com/privacy-and-security/risks/file-providers#do_not_use_the_root-path_path_element_in_the_configuration):
> `<root-path>` grants broad access to internal and external storage, increasing attack surface via `content://` URIs.
> Fix root path security issue

- ios/RNShare.mm
- src/types.ts
- website/docs/share-open.mdx
I noticed that RetroApp has a pretty cool feature that renders a custom preview for shared images.
I figured out how to achieve the same and thought it’d be great to share this little feature with the React Native community. Since I use this package every day, I’d love to contribute it here!
https://github.com/user-attachments/assets/1b52c00e-333c-42fd-ad92-49946648ea66
Sadly I haven't found a way to disable it on Android but below recorded that it's not breaking anything
| iOS | Android | 
| --- | --- |
| <video src="https://github.com/user-attachments/assets/65b12755-4a18-42d0-9aab-aaf2fa463f9f"> |  <video src="https://github.com/user-attachments/assets/f69abb93-bec1-41b4-937d-4e87597f6d38"> |
> feat: add ability to disable iOS overlay on bare share activity
